steps:
- name: 'node:10-alpine'
  entrypoint: "npm"
  args: ['ci']
- name: 'node:10-alpine'
  entrypoint: "npm"
  args: ['run', 'build']
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', "--project", "$_FIREBASE_PROJECT_ID", "--token", "$_FIREBASE_TOKEN"]